### ISSUE TITLE
404 not found Bid & offer history API

### ISSUE THREAD

**Issue by nakinthorn** [lnmarkets/docs.lnmarkets.com#6]
GET /history/bid-offer
https://api.lnmarkets.com/history/bid-offer

no this api bro

<img width="974" alt="Screen Shot 2564-02-03 at 14 13 42" src="https://user-images.githubusercontent.com/19216345/106711462-21ffbd80-662a-11eb-912f-476b98ea3a3c.png">

**Comment by vafanassieff** [comment]
It's not yet implemented our dev pushed to master branch and not to dev branch sorry !

**Comment by vafanassieff** [comment]
It's online !

:)
